### ISSUE TITLE
Error in Autoformer

### ISSUE THREAD

**Issue by chiyuzhang94** [MAZiqing/FEDformer#28]
I run Autoformer but get the following errors. 
According to this issue #5, I modified [this line](https://github.com/MAZiqing/FEDformer/blob/306add595141d262f02570b0150b5f9c2fbad0de/layers/AutoCorrelation.py#L35) to `self.use_wavelet = False`. 

Could you investigate the following issue?

```
Traceback (most recent call last):
  File "run.py", line 171, in <module>
    main()
  File "run.py", line 135, in main
    exp.train(setting)
  File "~/projects/time_forcast/FEDformer/exp/exp_main.py", line 141, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "~/fedformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/projects/time_forcast/FEDformer/models/Autoformer.py", line 85, in forward
    seasonal_init, trend_init = self.decomp(x_enc)
  File "~/fedformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/projects/time_forcast/FEDformer/layers/Autoformer_EncDec.py", line 50, in forward
    moving_mean = self.moving_avg(x)
  File "~/fedformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/projects/time_forcast/FEDformer/layers/Autoformer_EncDec.py", line 33, in forward
    front = x[:, 0:1, :].repeat(1, self.kernel_size - 1-math.floor((self.kernel_size - 1) // 2), 1)
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

Thanks.

**Comment by tianzhou2011** [comment]
I think you should change the kernel_size to be 25 for autoformer instead of a list of kernel value like we did in fedformer.  Please refer to https://github.com/thuml/Autoformer if you want to repeat autoformer's result. Because in the paper, we cite their experimental results without recalculation.

**Comment by chiyuzhang94** [comment]
Ok. I see. Got it!
