### ISSUE TITLE
ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by DLW30** [MAZiqing/FEDformer#55]
你好，当我将数据集改为illness时，发生了这样的错误，我知道可能要改变一些参数的设置，比如seq_len, label_len, pred_len，能告诉我具体应该如何更改吗？比如改变某个py文件中的函数的内容。
Traceback (most recent call last):
  File "C:\fedformer\FEDformer-master\run.py", line 170, in <module>
    main()
  File "C:\fedformer\FEDformer-master\run.py", line 134, in main
    exp.train(setting)
  File "C:\fedformer\FEDformer-master\exp\exp_main.py", line 88, in train
    vali_data, vali_loader = self._get_data(flag='val')
  File "C:\fedformer\FEDformer-master\exp\exp_main.py", line 36, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "C:\fedformer\FEDformer-master\data_provider\data_factory.py", line 44, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

**Comment by tianzhou2011** [comment]
你看一下shell scripts 里面跑illness的代码就好,确实很多参数和其他数据集不同
